[versions]
agp = "7.4.1"
android-compile = "android-30"
android-min = "21"
kotlin = "1.8.10"

[libraries]
assertj = { module = "org.assertj:assertj-core", version = "3.24.2" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "1.12.0" }
kotlin-parcelize-runtime = { module = "org.jetbrains.kotlin:kotlin-parcelize-runtime", version.ref = "kotlin" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version = "1.8.10-1.0.9" }
ksp-testing = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version = "1.4.9" }
robolectric = { module = "org.robolectric:robolectric", version = "4.9.2" }
tuulbox-logging = { module = "com.juul.tuulbox:logging", version = "6.4.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version = "1.7.20" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.13.0" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.24.0" }
one-eight = { id = "net.mbonnin.one.eight", version = "0.2" }
validator = { id = "binary-compatibility-validator", version = "0.8.0" }
