[versions]
agp = "8.0.2"
android-compile = "android-30"
android-min = "21"
jvm-toolchain = "11"
kotlin = "1.8.22"

[libraries]
assertj = { module = "org.assertj:assertj-core", version = "3.24.2" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "1.14.2" }
kotlin-parcelize-runtime = { module = "org.jetbrains.kotlin:kotlin-parcelize-runtime", version.ref = "kotlin" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version = "1.9.0-1.0.11" }
ksp-testing = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version = "1.5.0" }
robolectric = { module = "org.robolectric:robolectric", version = "4.10.3" }
tuulbox-logging = { module = "com.juul.tuulbox:logging", version = "6.4.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version = "1.8.20" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.15.0" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.25.3" }
validator = { id = "binary-compatibility-validator", version = "0.13.0" }
