[versions]
agp = "8.7.2"
android-compile = "30"
android-min = "21"
jvm-toolchain = "11"
kotlin = "2.0.21"

[libraries]
assertj = { module = "org.assertj:assertj-core", version = "3.26.3" }
khronicle = { module = "com.juul.khronicle:khronicle-core", version = "0.3.0" }
kotlin-parcelize-runtime = { module = "org.jetbrains.kotlin:kotlin-parcelize-runtime", version.ref = "kotlin" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "2.0.0" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version = "2.0.21-1.0.26" }
ksp-testing = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version = "1.6.0" }
robolectric = { module = "org.robolectric:robolectric", version = "4.13" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
api = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.16.3" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "4.4.1" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.30.0" }
