[versions]
agp = "8.3.0"
android-compile = "30"
android-min = "21"
jvm-toolchain = "11"
kotlin = "1.9.23"

[libraries]
assertj = { module = "org.assertj:assertj-core", version = "3.25.3" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "1.16.0" }
kotlin-parcelize-runtime = { module = "org.jetbrains.kotlin:kotlin-parcelize-runtime", version.ref = "kotlin" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version = "1.9.23-1.0.19" }
ksp-testing = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version = "1.5.0" }
robolectric = { module = "org.robolectric:robolectric", version = "4.11.1" }
tuulbox-logging = { module = "com.juul.tuulbox:logging", version = "7.2.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "4.2.0" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.27.0" }
validator = { id = "binary-compatibility-validator", version = "0.14.0" }
