name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-18.04

    env:
      GRADLE_ARGS: >-
        --no-daemon
        --max-workers 2
        -Pkotlin.incremental=false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-build-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Check
        run: ./gradlew $GRADLE_ARGS check jacocoTestReport

      - name: Keyring
        run: echo "${{ secrets.SIGNING_SECRET_KEY_RING }}" | base64 --decode > "$HOME/secring.gpg"

      - name: Publish Locally
        run: >-
          ./gradlew
          $GRADLE_ARGS
          --no-parallel
          -PVERSION_NAME=unspecified
          -Psigning.keyId="${{ secrets.SIGNING_KEY_ID }}"
          -Psigning.password="${{ secrets.SIGNING_PASSWORD }}"
          -Psigning.secretKeyRingFile="$HOME/secring.gpg"
          installArchives

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
