name: CI
on:
  pull_request:
  # Trigger on merges to `main` to allow `gradle/gradle-build-action` runs to write their caches.
  # https://github.com/gradle/gradle-build-action#using-the-caches-read-only
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew check jacocoTestReport

      - uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: '**/build/test-results/**/*.xml'
          report_individual_runs: 'true'

      - name: publishToMavenLocal
        if: github.repository_owner == 'JuulLabs'
        run: >
          ./gradlew
          -PVERSION_NAME=unspecified
          -PsigningInMemoryKey='${{ secrets.SIGNING_KEY }}'
          -PsigningInMemoryKeyPassword='${{ secrets.SIGNING_PASSWORD }}'
          publishToMavenLocal

      - uses: codecov/codecov-action@v4
